# not used it's just some typical content
FROM node:14 as frontend

# not used it's just some typical content
ARG CI=true

# this is all that's needed but the other
# content is likely to be present in a real
# project Dockerfile
FROM python:3.8-buster as backend

ARG POETRY_VERSION=1.4.2

# not used it's just some typical content
FROM backend as dev

# not used it's just some typical content
USER root
